package cn.yunqitong.ms.as.dao.client;

import cn.yunqitong.ms.as.dao.model.TVersion;
import cn.yunqitong.ms.as.dao.model.TVersionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    int countByExample(TVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    int deleteByExample(TVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    int insert(TVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    int insertSelective(TVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    List<TVersion> selectByExampleWithBLOBs(TVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    List<TVersion> selectByExample(TVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    TVersion selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    int updateByExampleSelective(@Param("record") TVersion record, @Param("example") TVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") TVersion record, @Param("example") TVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    int updateByExample(@Param("record") TVersion record, @Param("example") TVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    int updateByPrimaryKeySelective(TVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(TVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_version
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    int updateByPrimaryKey(TVersion record);
}