package cn.yunqitong.ms.as.dao.model;

import java.util.Date;

import cn.yunqitong.util.DateUtil;

public class TVersion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_version.name
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_version.firewirename
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    private String firewirename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_version.apppath
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    private String apppath;
    
    private String publishTime;

    public String getPublishTime() {
		return publishTime;
	}

	public void setPublishTime(String publishTime) {
		this.publishTime = publishTime;
	}
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_version.createtime
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    private Date createtime;
    
    //用于页面显示。
    private String createtimeString;
    public void setCreatetimeString(String createtimeString) {
		this.createtimeString = createtimeString;
	}

	public void setFirewiresizeStr(String firewiresizeStr) {
		this.firewiresizeStr = firewiresizeStr;
	}

	public String getCreatetimeString() {
		return DateUtil.getString(this.getCreatetime());
	}
    private String firewiresizeStr;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_version.firewiresize
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    private String firewiresize;

    public String getFirewiresizeStr() {
	    	String fs = this.getFirewiresize();
	    	if(fs != null && !fs.equals("")){
	    		return (Long.parseLong(fs)/1024/1024)+"";
	    	}
	    	return "";
	}
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_version.remark
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_version.platform
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    private String platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_version.filemd5
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    private String filemd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_version.build
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    private String build;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_version.file
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    private byte[] file;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_version.name
     *
     * @return the value of t_version.name
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_version.name
     *
     * @param name the value for t_version.name
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_version.firewirename
     *
     * @return the value of t_version.firewirename
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    public String getFirewirename() {
        return firewirename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_version.firewirename
     *
     * @param firewirename the value for t_version.firewirename
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    public void setFirewirename(String firewirename) {
        this.firewirename = firewirename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_version.apppath
     *
     * @return the value of t_version.apppath
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    public String getApppath() {
        return apppath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_version.apppath
     *
     * @param apppath the value for t_version.apppath
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    public void setApppath(String apppath) {
        this.apppath = apppath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_version.createtime
     *
     * @return the value of t_version.createtime
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_version.createtime
     *
     * @param createtime the value for t_version.createtime
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_version.firewiresize
     *
     * @return the value of t_version.firewiresize
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    public String getFirewiresize() {
        return firewiresize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_version.firewiresize
     *
     * @param firewiresize the value for t_version.firewiresize
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    public void setFirewiresize(String firewiresize) {
        this.firewiresize = firewiresize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_version.remark
     *
     * @return the value of t_version.remark
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_version.remark
     *
     * @param remark the value for t_version.remark
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_version.platform
     *
     * @return the value of t_version.platform
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_version.platform
     *
     * @param platform the value for t_version.platform
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    public void setPlatform(String platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_version.filemd5
     *
     * @return the value of t_version.filemd5
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    public String getFilemd5() {
        return filemd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_version.filemd5
     *
     * @param filemd5 the value for t_version.filemd5
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    public void setFilemd5(String filemd5) {
        this.filemd5 = filemd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_version.build
     *
     * @return the value of t_version.build
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    public String getBuild() {
        return build;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_version.build
     *
     * @param build the value for t_version.build
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    public void setBuild(String build) {
        this.build = build;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_version.file
     *
     * @return the value of t_version.file
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    public byte[] getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_version.file
     *
     * @param file the value for t_version.file
     *
     * @mbggenerated Sun Nov 08 18:33:45 CST 2015
     */
    public void setFile(byte[] file) {
        this.file = file;
    }
}